version: '3.8'

services:
  hightable_backend:
    build: .
    container_name: hightable-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      # REDIS_URL: redis://redis:6379
    volumes:
      - .:/workspace:cached
    networks:
      - continental 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api_hightable.rule=Host(`api.mastervip.vn`)"
      - "traefik.http.routers.api_hightable.entrypoints=web,websecure"
      - "traefik.http.routers.api_hightable.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api_hightable.tls=true"
      - "traefik.http.services.api_hightable.loadbalancer.server.port=3000"
    command: >
      /bin/sh -c "while sleep 1000; do :; done"


  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - continental 

networks:
  continental :
    external: true

# Create networks
# docker network create continental